### ISSUE TITLE
Cannot create invoice with invoices/create/invoice

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#112] opened 2023-01-27 14:33 UTC
Not able to create invoice using merging branch, below is the body json for the invoice and looking at the error, my assumption is it is searching for the name and address, instead of creating a new one

**Body json for creating the invoice:**
{   
    "name": "Test Invoice",
	"account": "8AzZP72ok5QY5jz88jASjkfRVDw5PFmTzmbjLTJTsisX68nyZs5",
    "recipient": "Test",
    "reference": "Software Services",
    "description": "Application Development",
    "number": "001",
	"sender_detail": "Aeon",
    "recipient_detail": "Test",
    "session": "ef0b5068fde394823edda190ca9a657112caf959b23b2b73bdd2cc855c3d18fc",
	"pin": 1234,
  	"items": [
          {
              "description": "Prototyping",
              "units": 1,
              "amount": 50.5
          },
		  {
              "description": "MVP",
              "units": 1.25,
              "amount": 70.5
          },
          {
              "description": "Consultation",
              "units": 2.35,
              "amount": 20
          }
      ]
      
}

**With the above body json get the following error:**

{
    "error": {
        "code": -13,
        "message": "Object not found"
    },
    "info": {
        "method": "invoices/create",
        "status": "active",
        "address": "117.248.85.104:58709",
        "latency": "0.119000 ms"
    }
}

**If the invoice "name" is removed from the invoice body json, we get the following error:**
{
    "error": {
        "code": -56,
        "message": "Missing Parameter [name/address]"
    },
    "info": {
        "method": "invoices/create",
        "status": "active",
        "address": "117.248.85.104:21632",
        "latency": "0.086961 ms"
    }
}

**Comment by VidereLicet** [comment] 2023-02-03 11:59
Will make an endpoint that can POST this JSON, I test on the CLI so it's a bit more difficult to input more complex parameters such as this. Need to do that anyhow, once I have that done can replicate and figure out what the issue is.

**Comment by VidereLicet** [comment] 2023-02-03 12:16
Fixed with commit 26747aa86f8cbc977d80f2689de83f83eee590b0

**Closed by VidereLicet** 2023-02-03 12:16 UTC
